
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 29 17:33:38 BRT 2016
//----------------------------------------------------

package modelo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int THI = 44;
  public static final int DIVIDE = 9;
  public static final int RET = 37;
  public static final int MAI = 33;
  public static final int STR = 34;
  public static final int SEMI = 10;
  public static final int FCO = 26;
  public static final int INT = 38;
  public static final int LESS = 16;
  public static final int MINUS = 8;
  public static final int FCH = 24;
  public static final int STA = 31;
  public static final int PUB = 30;
  public static final int AND = 2;
  public static final int VIR = 28;
  public static final int OR = 5;
  public static final int EXT = 35;
  public static final int NUL = 45;
  public static final int PLUS = 7;
  public static final int IF = 4;
  public static final int VOI = 32;
  public static final int EOF = 0;
  public static final int PTO = 22;
  public static final int GTR = 15;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int RT_PAREN = 13;
  public static final int IDENT = 21;
  public static final int TRU = 42;
  public static final int VOID = 12;
  public static final int EQ = 14;
  public static final int ASSMNT = 20;
  public static final int WHI = 39;
  public static final int TIMES = 6;
  public static final int NEG = 27;
  public static final int ELSE = 3;
  public static final int BOO = 36;
  public static final int NOT_EQ = 19;
  public static final int CLA = 29;
  public static final int SOP = 40;
  public static final int ACO = 25;
  public static final int LESS_EQ = 17;
  public static final int LEFT_PAREN = 11;
  public static final int ACH = 23;
  public static final int LEN = 41;
  public static final int FAL = 43;
  public static final int GTR_EQ = 18;
}

